// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoUN9CjxRyPBPyNnI1eCoZIP76gNbzekA',
    appId: '1:358479882207:web:ede857f37ce99412d2466a',
    messagingSenderId: '358479882207',
    projectId: 'mad2-2023',
    authDomain: 'mad2-2023.firebaseapp.com',
    storageBucket: 'mad2-2023.appspot.com',
    measurementId: 'G-C5LN4KN01D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfhSAF9AXVsTfz4vpcGj71lgZI1UNp_Go',
    appId: '1:358479882207:android:4beef216f784c016d2466a',
    messagingSenderId: '358479882207',
    projectId: 'mad2-2023',
    storageBucket: 'mad2-2023.appspot.com',
  );
}
